# Generated by Django 3.1.4 on 2022-02-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('mens', 'Mens'), ('womens', 'Womens')], default='mens', max_length=10),
        ),
    ]
