# Generated by Django 3.1.4 on 2022-02-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20220214_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('womens', 'Womens'), ('mens', 'Mens')], default='mens', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='post', help_text='This field should be unique', max_length=200),
        ),
    ]
