# Generated by Django 3.1.4 on 2022-02-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20220214_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('womens', 'Womens'), ('mens', 'Mens')], default='mens', max_length=10),
        ),
    ]
