# Generated by Django 3.1.4 on 2022-02-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20220221_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('book', 'Book'), ('merch', 'Merch')], default='book', max_length=10),
        ),
    ]
