# Generated by Django 3.1.4 on 2022-04-16 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0048_orderitem_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='address',
        ),
    ]
