# Generated by Django 3.1.4 on 2022-04-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0050_auto_20220417_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('book', 'Book'), ('merch', 'Merch')], default='book', max_length=10),
        ),
    ]
