# Generated by Django 3.1.4 on 2022-03-08 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0002_auto_20220308_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freelance',
            old_name='Projects_url',
            new_name='Projects_links',
        ),
    ]
