# Generated by Django 3.1.4 on 2022-03-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0003_auto_20220308_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelance',
            name='Projects_links',
            field=models.TextField(blank=True, null=True),
        ),
    ]
