# Generated by Django 3.1.4 on 2022-03-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0005_auto_20220308_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelance',
            name='Projects_links',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
