# Generated by Django 3.1.4 on 2022-03-08 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0007_auto_20220308_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelance',
            name='Projects_links',
        ),
        migrations.RemoveField(
            model_name='freelance',
            name='projects_done',
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('freelance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='freelance.freelance')),
                ('projects_done', models.TextField(blank=True, max_length=100, null=True)),
                ('Projects_links', models.URLField(blank=True, max_length=100, null=True)),
            ],
            bases=('freelance.freelance',),
        ),
    ]
