# Generated by Django 3.1.4 on 2022-03-08 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0008_auto_20220308_1801'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
