# Generated by Django 3.1.4 on 2022-03-08 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0009_delete_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects_done', models.TextField(blank=True, max_length=100, null=True)),
                ('Projects_links', models.URLField(blank=True, max_length=100, null=True)),
                ('freelance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelance.freelance')),
            ],
        ),
    ]
