# Generated by Django 3.1.4 on 2022-03-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0010_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelance',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnail'),
        ),
    ]
