# Generated by Django 3.1.4 on 2022-03-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0011_freelance_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelance',
            name='skills',
        ),
        migrations.AddField(
            model_name='freelance',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='skills',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
