# Generated by Django 3.1.4 on 2022-03-08 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0012_auto_20220308_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freelance',
            old_name='thumbnail',
            new_name='fthumbnail',
        ),
    ]
