# Generated by Django 3.1.4 on 2022-03-08 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0013_auto_20220308_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freelance',
            old_name='fthumbnail',
            new_name='thumbnail',
        ),
    ]
