# Generated by Django 3.1.4 on 2022-03-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0014_auto_20220308_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelance',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
