# Generated by Django 3.1.4 on 2022-03-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0017_fcontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcontact',
            name='budget',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fcontact',
            name='contact_no',
            field=models.IntegerField(),
        ),
    ]
