# Generated by Django 3.1.4 on 2022-03-10 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0018_auto_20220310_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcontact',
            name='freelance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='freelance.freelance'),
        ),
    ]
