# Generated by Django 3.1.4 on 2022-03-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0020_remove_projects_projects_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelance',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
