# Generated by Django 3.1.4 on 2022-04-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0021_freelance_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fcontact',
            options={'ordering': ('-date_contacted',)},
        ),
        migrations.AddField(
            model_name='fcontact',
            name='date_contacted',
            field=models.DateTimeField(auto_now_add=True, default=120222),
            preserve_default=False,
        ),
    ]
