# Generated by Django 3.1.4 on 2022-04-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0023_auto_20220417_1247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fcontact',
            options={'ordering': ('-date_contacted',)},
        ),
        migrations.AddField(
            model_name='fcontact',
            name='date_contacted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
