# Generated by Django 3.1.4 on 2022-02-23 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='tirle',
            new_name='title',
        ),
    ]
