# Generated by Django 3.1.4 on 2022-02-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20220224_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
