# Generated by Django 3.1.4 on 2022-03-12 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_course_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='resource',
        ),
    ]
