# Generated by Django 3.1.4 on 2022-03-13 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_remove_course_resource'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('-date',)},
        ),
    ]
