# Generated by Django 3.1.4 on 2022-01-27 12:32

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20220127_1801'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogManager',
        ),
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('blogmanager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='draft', max_length=10),
        ),
    ]
